### ISSUE TITLE
DataPuller using an insane amount of CPU in BeatSaber.

### ISSUE THREAD

**Issue by joshuasuperboy** [kOFReadie/DataPuller#1]
Ok so recently i have installed one of your mods for BeatSaber called DataPuller. After a while of playing any map in beatsaber my game starts to use up more and more CPU gradually. It then started to use so much of my CPU that my CPU has gotten to 100%. Also having the game paused more more than 10 minutes then unpausing it causes BeatSaber to use up 100% of my CPU. I then started to remove mods one by one. Then i deleted DataPuller next and it fixed it. Then just to make sure it was DataPuller. I have completely deleted the BeatSaber folder and then i reinstalled BeatSaber and the mod loader then i put DataPuller back in and that is all. Then the issue occurred again. Then just to see if it was for sure DataPuller that was causing the issue. I then removed DataPuller and then my BeatSaber was fine again. I have a overclocked i5 9600K At 5GHz and BeatSaber should not be using 100% of it. I sent two pictures below showing with DataPuller installed and it without it installed. Keep in mind that i was having a map being played when i took those screenshots.

With DataPuller installed while playing a map.
![2020 05 25-23 27](https://user-images.githubusercontent.com/32559193/82862446-41641980-9ee5-11ea-8e01-9a5a2c210d5e.png)
With DataPuller not installed while playing a map.
![2020 05 25-23 53](https://user-images.githubusercontent.com/32559193/82862511-6d7f9a80-9ee5-11ea-9f43-940b58a30400.png)
Now you see the issue. DataPuller is causing BeatSaber to use all of my CPU while having the game paused for long enough. Or when playing a beatsaber map for long enough. So for right now i will be waiting for this to get fixed and i will not have the DataPuller mod installed. I just decided to let you know of this issue with DataPuller.

**Comment by kOFReadie** [comment]
Odd, Ill look into it, thanks.

**Comment by kOFReadie** [comment]
@joshuasuperboy I've made some small changes that may help with the CPU usage going up over time, I tested the game with my old mod (29%CPU avg), no mod (23% avg) and the tweaked mod (24% avg) I'm unsure why it was behaving so oddly, ill keep investigating it but could you try this tweaked version and tell me if it is any better. 
[DataPuller.zip](https://github.com/kOFReadie/DataPuller/files/4681268/DataPuller.zip)

**Comment by wgzeyu** [comment]
same issues
After installing this mod, in the second half of the song, BS exhausted 100% of CPU
But since I'm scoring, I don't want to test first ...

**Comment by kOFReadie** [comment]
Wgzeyu was this with the latest release? If so than back to looking for the problems

**Comment by wgzeyu** [comment]
No, it is the first release.
This problem is not 100% reproducible. It was working fine when I first started using it. It only appeared after I used it for a while.
However, when the problem occurs, I will encounter it every time I play the map.
(I ’m not sure if restarting the game will solve it, I uninstalled the plugin at the time)

**Comment by kOFReadie** [comment]
Could you try the second release then please, I think ive fixed it but im unsure

**Comment by joshuasuperboy** [comment]
Yes i will sorry been busy with things.
